# Generated by Django 2.2.28 on 2022-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressywjykjhycd'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressywjykjhycd',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
